import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const root=fileURLToPath(new URL('../../',import.meta.url));
const epoch=Date.UTC(2026,8,27,12);
async function table(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.TABLE_BROWSER_EXECUTABLE});
 const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!=='http://table.test')return route.fulfill({status:200,contentType:'text/javascript',body:''});const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root))return route.abort();try{const body=await readFile(file);const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};await route.fulfill({status:200,contentType:mime[path.extname(file)]||'application/octet-stream',body});}catch{await route.fulfill({status:404,body:''});}});
 await page.addInitScript(({epoch})=>{const c=window.__test={now:epoch,seed:123456789,random:0,packets:[],timers:new Map(),next:1};const NativeDate=Date;window.Date=class extends NativeDate{constructor(...a){super(...(a.length?a:[c.now]));}static now(){return c.now;}};Math.random=()=>{c.random++;c.seed=(Math.imul(c.seed,1664525)+1013904223)>>>0;return c.seed/4294967296;};const add=(kind,fn,delay=0)=>{const id=c.next++;c.timers.set(id,{kind,fn,delay:Number(delay),due:c.now+Number(delay)});return id;};window.setTimeout=(fn,d)=>add('timeout',fn,d);window.setInterval=(fn,d)=>add('interval',fn,d);window.clearTimeout=window.clearInterval=id=>c.timers.delete(id);window.requestAnimationFrame=fn=>add('frame',fn,16);window.cancelAnimationFrame=id=>c.timers.delete(id);c.advance=ms=>{c.now+=ms;};c.reset=()=>{c.now=epoch;c.seed=123456789;c.random=0;c.packets.length=0;};localStorage.setItem('table.v3.prefs',JSON.stringify({sound:false,motion:false,immersive:true,fast:false,light:false}));},{epoch});
 await page.goto('http://table.test/jeux.html');await page.evaluate(()=>{if(typeof houseEightAct!=='function'||typeof legacyCactusQuickUI!=='function')throw Error('final overrides missing');__test.connection=()=>({open:true,send:p=>__test.packets.push(JSON.parse(JSON.stringify(p))),close(){}});});return{browser,page,errors};}
const clone=v=>JSON.parse(JSON.stringify(v));
async function setup(page,id='huit',mode='solo',timed=false){return page.evaluate(({id,mode,timed})=>{__test.reset();net=freshNetwork();prefs.motion=false;prefs.sound=false;prefs.fast=false;prefs.immersive=true;applyPrefs();S=createGame(id,{mode,names:['A','B','C'],timeControl:{enabled:timed,initial:120,bonus:10,drawBonus:10}});view='game';gate=false;busy=false;selection.clear();showSuit=null;if(mode==='online'){net.active=true;net.role='host';net.me=0;net.connected=true;net.started=true;net.status='playing';net.matchId='test';net.revision=1;net.state=S;net.seats=S.players.map(p=>({name:p.name,lastSeq:0,conn:__test.connection()}));net.conn=__test.connection();S=projectGame(net.state,0);}renderGame(false);return Object.keys(GAMES);},{id,mode,timed});}
async function clean(page){return page.evaluate(()=>({state:clone(S),random:__test.random,packets:clone(__test.packets)}));}
let browser;
test('22 final game definitions survive repeated 2D refreshes',async()=>{const t=await table();browser=t.browser;try{const games=await setup(t.page);assert.equal(games.length,22);for(const id of games){await setup(t.page,id);const before=await clean(t.page);await t.page.evaluate(()=>{for(let i=0;i<5;i++)renderGame(false);});assert.deepEqual(await clean(t.page),before,id);}assert.deepEqual(t.errors,[]);}finally{await browser.close();}});
test('same seed and actions are independent of extra frames',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const run=extra=>t.page.evaluate(extra=>{const trace=[];for(let i=0;i<6&&S.phase!=='over';i++){const a=ai(S);trace.push({a,ok:act(S,a)});if(extra)for(let j=0;j<3;j++)renderGame(false);}return{state:clone(S),trace,random:__test.random};},extra);const a=await run(false);await setup(t.page);const b=await run(true);assert.deepEqual(b,a);}finally{await browser.close();}});
test('render is timing-neutral while the session tick settles the clock',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.clock.running=true;S.clock.lastAt=Date.now();const before=clone(S.clock);__test.advance(4000);renderGame(false);const afterRender=clone(S.clock);timingTick();const afterTick=clone(S.clock);return{before,afterRender,afterTick};});assert.deepEqual(r.afterRender,r.before);assert.equal(r.afterRender.remaining[0]-r.afterTick.remaining[0],4000);}finally{await browser.close();}});
test('session scheduling owns the clock run-state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.clock.running=false;S.clock.lastAt=Date.now();schedule();const afterSchedule=clone(S.clock);renderGame(false);return{afterSchedule,afterRender:clone(S.clock)};});assert.equal(r.afterSchedule.running,true);assert.deepEqual(r.afterRender,r.afterSchedule);}finally{await browser.close();}});
test('final guest handler preserves the authenticated seat index',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');const r=await t.page.evaluate(()=>{net.state.turn=2;const n=net.state.players[2].hand.length;handleGuestAction({seq:1,revision:1,matchId:'test',action:{type:'draw'}},2);return{drawn:net.state.players[2].hand.length-n,seq:net.seats[2].lastSeq,otherSeq:net.seats[1].lastSeq};});assert.deepEqual(r,{drawn:1,seq:1,otherSeq:0});}finally{await browser.close();}});
test('Cactus quick throw uses the authenticated guest seat even out of turn',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'cactus','online');const r=await t.page.evaluate(()=>{net.state.phase='draw';net.state.turn=0;const owner=2,index=net.state.players[owner].hand.findIndex(Boolean),card=net.state.players[owner].hand[index];net.state.discard[net.state.discard.length-1]={...net.state.discard.at(-1),rank:card.rank};const before=legacyCactusCount(net.state.players[owner]);handleGuestAction({seq:1,revision:1,matchId:'test',action:{type:'quick',index}},owner);return{removed:before-legacyCactusCount(net.state.players[owner]),owner:net.state.lastQuick?.owner,seq:net.seats[owner].lastSeq,otherSeq:net.seats[1].lastSeq,turn:net.state.turn};});assert.deepEqual(r,{removed:1,owner:2,seq:1,otherSeq:0,turn:0});}finally{await browser.close();}});
test('clock expiration uses the restored Eight rules',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.turn=0;S.phase='play';S.pendingDraw=6;S.attack='A';S.blockEight=false;S.clock.remaining[0]=0;S.clock.running=false;const before=S.players[0].hand.length;const ok=clockExpire(S,Date.now());return{ok,drawn:S.players[0].hand.length-before,pendingDraw:S.pendingDraw,attack:S.attack,turn:S.turn,reserve:S.clock.remaining[0]};});assert.equal(r.ok,true);assert.equal(r.drawn,6);assert.equal(r.pendingDraw,0);assert.equal(r.attack,null);assert.notEqual(r.turn,0);assert.equal(r.reserve,20000);}finally{await browser.close();}});
test('view controller switches renderers without touching game or network state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');const before=await clean(t.page);const r=await t.page.evaluate(async()=>{const calls=[];SalonTableView.register('test3d',{activate(){calls.push('activate')},render(payload){calls.push({gameId:payload.gameId,privateIndex:payload.privateIndex,online:payload.online,stateId:payload.state?.id})},deactivate(){calls.push('deactivate')}});const switched=await SalonTableView.setMode('test3d',{persistPreference:false});renderGame(false);const mode3d=SalonTableView.getMode();const back=await SalonTableView.setMode('2d',{persistPreference:false});return{switched,back,mode3d,mode2d:SalonTableView.getMode(),calls,hasStateView:Object.hasOwn(S,'tableView')||Object.hasOwn(S,'viewMode'),hasNetView:Object.hasOwn(net,'tableView')||Object.hasOwn(net,'viewMode')};});const after=await clean(t.page);assert.equal(r.switched.ok,true);assert.equal(r.mode3d,'test3d');assert.equal(r.back.ok,true);assert.equal(r.mode2d,'2d');assert.equal(r.hasStateView,false);assert.equal(r.hasNetView,false);assert.ok(r.calls.some(x=>typeof x==='object'&&x.gameId==='huit'&&x.privateIndex===0&&x.online===true&&x.stateId==='huit'));assert.deepEqual(after,before);}finally{await browser.close();}});

test('unavailable 3D leaves the effective renderer in 2D',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const before=await clean(t.page);const r=await t.page.evaluate(async()=>{SalonTableView.register('3d',{available:()=>false});const result=await SalonTableView.setMode('3d',{persistPreference:false});return{result,mode:SalonTableView.getMode(),dataset:document.documentElement.dataset.tableView};});assert.equal(r.result.ok,false);assert.equal(r.result.reason,'unavailable');assert.equal(r.mode,'2d');assert.equal(r.dataset,'2d');assert.deepEqual(await clean(t.page),before);}finally{await browser.close();}});

test('returning to 2D cancels a late asynchronous 3D activation',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const r=await t.page.evaluate(async()=>{let release;SalonTableView.register('3d',{prepare(){return new Promise(resolve=>{release=resolve})},render(){throw Error('late 3D render must not run')}});const pending=SalonTableView.setMode('3d',{persistPreference:false});await Promise.resolve();const back=await SalonTableView.setMode('2d',{persistPreference:false});release();const first=await pending;return{first,back,mode:SalonTableView.getMode(),dataset:document.documentElement.dataset.tableView};});assert.equal(r.back.ok,true);assert.equal(r.first.ok,false);assert.equal(r.first.reason,'superseded');assert.equal(r.mode,'2d');assert.equal(r.dataset,'2d');}finally{await browser.close();}});
test('supported games expose one exclusive 2D/3D return button and fullscreen-first shell without mutating online state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');await t.page.evaluate(()=>{SalonTableView.register('3d',{available:()=>document.documentElement.dataset.table3dSupported==='yes',render(){}});renderGame(false);});assert.equal(await t.page.locator('.table-view-switch').count(),1);assert.equal(await t.page.locator('.table-view-switch button').count(),1);assert.equal((await t.page.locator('.table-view-switch button').textContent())?.trim(),'3D');const before=await clean(t.page);await t.page.click('[data-table-view-mode="3d"]');await t.page.waitForFunction(()=>SalonTableView.getMode()==='3d');assert.deepEqual(await clean(t.page),before);assert.equal(await t.page.evaluate(()=>document.documentElement.dataset.table3dPresentation),'full');assert.equal((await t.page.locator('.table-view-switch button').textContent())?.trim(),'2D');const hidden=await t.page.evaluate(()=>({board:getComputedStyle(document.querySelector('.scene-surface')).display,hand:getComputedStyle(document.querySelector('.hand-panel')).display}));assert.equal(hidden.board,'none');assert.equal(hidden.hand,'none');await t.page.evaluate(()=>{const b=document.createElement('button');b.id='test-3d-minimize';b.dataset.table3dWindow='embedded';document.body.append(b)});await t.page.evaluate(()=>document.getElementById('test-3d-minimize').click());assert.equal(await t.page.evaluate(()=>document.documentElement.dataset.table3dPresentation),'embedded');await t.page.evaluate(()=>{const b=document.createElement('button');b.id='test-3d-expand';b.dataset.table3dWindow='full';document.body.append(b)});await t.page.evaluate(()=>document.getElementById('test-3d-expand').click());assert.equal(await t.page.evaluate(()=>document.documentElement.dataset.table3dPresentation),'full');await t.page.click('[data-table-view-mode="2d"]');await t.page.waitForFunction(()=>SalonTableView.getMode()==='2d');assert.deepEqual(await clean(t.page),before);assert.equal(await t.page.evaluate(()=>document.documentElement.hasAttribute('data-table3d-presentation')),false);assert.equal((await t.page.locator('.table-view-switch button').textContent())?.trim(),'3D');const restored=await t.page.evaluate(()=>({board:getComputedStyle(document.querySelector('.scene-surface')).display,hand:getComputedStyle(document.querySelector('.hand-panel')).display}));assert.notEqual(restored.board,'none');assert.notEqual(restored.hand,'none');for(const id of ['oie','yam','boite','cactus','rummikub','president','menteur','suites','plis','encheres','pouilleux','quatrevingtdixneuf','vingtetun','bataille','metropole','echo','ballon','anagrammes','intrus','code','golf']){await setup(t.page,id,'online');assert.equal(await t.page.locator('.table-view-switch').count(),1,id);assert.equal(await t.page.locator('.table-view-switch button').count(),1,id);}}finally{await browser.close();}});

test('privacy gate withholds state from an active 3D renderer',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','local');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={state:payload.state,gated:payload.gated,canInteract:payload.canInteract}}});await SalonTableView.setMode('3d',{persistPreference:false});gate=true;seen=null;renderGame(false);return{seen,mode:SalonTableView.getMode()};});assert.equal(r.mode,'3d');assert.equal(r.seen.gated,true);assert.equal(r.seen.canInteract,false);assert.equal(r.seen.state,null);}finally{await browser.close();}});

test('3D interaction payload pauses while Eight waits for a suit choice',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={canInteract:payload.canInteract,playable:[...payload.viewData.playableIds]}}});await SalonTableView.setMode('3d',{persistPreference:false});showSuit='synthetic-choice';renderGame(false);return seen;});assert.equal(r.canInteract,false);assert.deepEqual(r.playable,[]);}finally{await browser.close();}});

test('Eight touch drag to discard opens the suit choice and always cleans its ghost',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo');const r=await t.page.evaluate(()=>{S.turn=0;S.phase='play';S.pendingDraw=0;S.attack=null;S.blockEight=false;S.suit='C';S.discard=[{id:'touch-top',suit:'C',rank:9}];S.players[0].hand=[{id:'touch-eight',suit:'H',rank:8},{id:'touch-four',suit:'C',rank:4}];showSuit=null;renderGame(false);const card=document.querySelector('[data-eight-card="1"][data-id="touch-eight"]'),drop=document.querySelector('[data-eight-drop="1"]');if(!card||!drop)throw Error('Eight drag fixtures missing');const a=card.getBoundingClientRect(),b=drop.getBoundingClientRect(),start={x:a.left+a.width/2,y:a.top+a.height/2},end={x:b.left+b.width/2,y:b.top+b.height/2},event=(type,x,y)=>new PointerEvent(type,{bubbles:true,cancelable:true,pointerId:77,pointerType:'touch',isPrimary:true,button:0,buttons:type==='pointerup'?0:1,clientX:x,clientY:y});card.dispatchEvent(event('pointerdown',start.x,start.y));document.dispatchEvent(event('pointermove',end.x,end.y));const during={ghost:document.querySelectorAll('.eight-drag-ghost').length,source:document.querySelectorAll('.eight-drag-source').length,hot:document.querySelector('[data-eight-drop="1"]')?.classList.contains('eight-drop-hot')};document.dispatchEvent(event('pointerup',end.x,end.y));return{during,showSuit,ghost:document.querySelectorAll('.eight-drag-ghost').length,source:document.querySelectorAll('.eight-drag-source').length,hot:document.querySelector('[data-eight-drop="1"]')?.classList.contains('eight-drop-hot')||false};});assert.deepEqual(r.during,{ghost:1,source:1,hot:true});assert.equal(r.showSuit,'touch-eight');assert.equal(r.ghost,0);assert.equal(r.source,0);assert.equal(r.hot,false);}finally{await browser.close();}});

test('Goose exposes engine-derived destinations to the 3D renderer',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'oie','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={gameId:payload.gameId,coords:payload.viewData.boardCoords.length,geese:[...payload.viewData.gooseCells],choices:payload.viewData.gooseChoices.map(x=>({...x}))}}});S.goosePending={i:S.turn,dice:[2,5],rerolls:0};S.dice=[2,5];const expected=[2,5,7].map(steps=>({steps,target:legacyGooseTarget(player(S).pos,steps)}));renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return{seen,expected,switches:document.querySelectorAll('.table-view-switch').length};});assert.equal(r.seen.gameId,'oie');assert.equal(r.seen.coords,63);assert.deepEqual(r.seen.choices,r.expected);assert.equal(r.switches,1);}finally{await browser.close();}});

test('Three.js table renderer never draws gameplay randomness',async()=>{const source=await readFile(path.join(root,'shared/table-3d.js'),'utf8');assert.equal(source.includes('Math.random'),false);assert.match(source,/Array\.isArray\(s\?\.dice\).*s\.dice/);});

test('Yam exposes engine-owned dice and held state to the 3D renderer',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'yam','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={dice:[...payload.viewData.yamDice],held:[...payload.viewData.yamHeld],rolls:payload.viewData.yamRolls,turn:payload.viewData.yamTurn,interactions:payload.interactions}}});S.dice=[6,2,6,4,1];S.held=[true,false,true,false,false];S.rolls=2;renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const initial={dice:[...seen.dice],held:[...seen.held],rolls:seen.rolls,turn:seen.turn},before=clone(S),action=seen.interactions.yam;action('hold',1);return{seen:initial,before,after:clone(S)};});assert.deepEqual(r.seen.dice,[6,2,6,4,1]);assert.deepEqual(r.seen.held,[true,false,true,false,false]);assert.equal(r.seen.rolls,2);assert.equal(r.after.held[1],true);assert.equal(r.after.moves,r.before.moves+1);assert.deepEqual(r.after.dice,r.before.dice);assert.equal(r.after.rolls,r.before.rolls);assert.equal(r.after.turn,r.before.turn);assert.equal(r.after.players[0].score,r.before.players[0].score);}finally{await browser.close();}});

test('Shut the Box exposes open tiles, dice and local selection to 3D',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'boite','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={dice:[...payload.viewData.boxDice],numbers:[...payload.viewData.boxNumbers],selected:[...payload.viewData.boxSelected],stage:payload.viewData.boxStage,canOne:payload.viewData.boxCanOne,interactions:payload.interactions}}});S.boxDice=[3,4];S.boxNumbers=[1,2,3,4,5,6];S.boxStage='choose';selection.clear();renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const stateBefore=clone(S);seen.interactions.box('toggle',3);const stateAfter=clone(S);return{first:{dice:seen.dice,numbers:seen.numbers,stage:seen.stage,canOne:seen.canOne},selected:[...selection].map(Number),stateBefore,stateAfter};});assert.deepEqual(r.first.dice,[3,4]);assert.deepEqual(r.first.numbers,[1,2,3,4,5,6]);assert.equal(r.first.stage,'choose');assert.equal(r.first.canOne,true);assert.deepEqual(r.selected,[3]);assert.deepEqual(r.stateAfter,r.stateBefore);}finally{await browser.close();}});

test('generic 3D card selection stays local and network-neutral',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'president','online');const r=await t.page.evaluate(async()=>{S.turn=0;let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={selected:[...payload.viewData.selectedIds],selectable:[...payload.viewData.selectableIds],interactions:payload.interactions}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const id=S.players[0].hand[0].id,before={state:clone(S),random:__test.random,packets:clone(__test.packets)},select=seen.interactions.cardSelect;select(id);return{id,selected:[...selection],before,after:{state:clone(S),random:__test.random,packets:clone(__test.packets)}};});assert.deepEqual(r.selected,[r.id]);assert.deepEqual(r.after,r.before);}finally{await browser.close();}});

test('Suites and Tricks playable cards are derived from their existing rule engines',async()=>{const t=await table();browser=t.browser;try{for(const id of ['suites','plis']){await setup(t.page,id,'solo');const r=await t.page.evaluate(async id=>{S.turn=0;gate=false;let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=[...payload.viewData.cardPlayableIds]}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const expected=player(S).hand.filter(c=>id==='suites'?suitesLegal(S,c):tricksLegal(S,c)).map(c=>c.id);return{seen,expected};},id);assert.deepEqual(r.seen,r.expected,id);await t.page.evaluate(()=>SalonTableView.setMode('2d',{persistPreference:false}));}}finally{await browser.close();}});

test('Auction 3D payload preserves projected hidden bids',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'encheres','online');const r=await t.page.evaluate(async()=>{net.state.phase='play';net.state.turn=0;net.state.bids[1]=clone(net.state.players[1].hand[0]);S=projectGame(net.state,0);let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){const bid=payload.viewData.cardCenter.bids[1];seen={hidden:!!bid?.hidden,hasRank:!!bid&&Object.hasOwn(bid,'rank'),id:bid?.id,sourceRank:net.state.bids[1].rank}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return seen;});assert.equal(r.hidden,true);assert.equal(r.hasRank,false);assert.match(r.id,/^sealed-/);assert.equal(Number.isInteger(r.sourceRank),true);}finally{await browser.close();}});

test('Old Maid 3D target uses only projected hidden cards',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'pouilleux','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={maid:{...payload.viewData.maid},targetCards:payload.state.players[payload.viewData.maid.target].hand.map(c=>({...c}))}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return seen;});assert.equal(r.targetCards.length,r.maid.targetCount);assert.equal(r.targetCards.every(c=>c.hidden===true),true);assert.equal(r.targetCards.some(c=>Object.hasOwn(c,'rank')),false);}finally{await browser.close();}});

test('99 card selection stays local and network-neutral in 3D',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'quatrevingtdixneuf','online');const r=await t.page.evaluate(async()=>{S.turn=0;let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={ninety:{...payload.viewData.ninety},interactions:payload.interactions}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const id=S.players[0].hand[0].id,before={state:clone(S),random:__test.random,packets:clone(__test.packets)},select=seen.interactions.specialCard;select('select',id);return{id,selected:[...selection],before,after:{state:clone(S),random:__test.random,packets:clone(__test.packets)}};});assert.deepEqual(r.selected,[r.id]);assert.deepEqual(r.after,r.before);}finally{await browser.close();}});

test('Blackjack 3D payload preserves the hidden dealer card',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'vingtetun','online');const r=await t.page.evaluate(async()=>{const source=net.state,first=clone(source.deck.at(-1)),second=clone(source.deck.at(-2));source.dealer=[first,second];source.dealerRevealed=false;source.phase='play';source.turn=0;source.players[0].hand=[clone(source.deck.at(-3)),clone(source.deck.at(-4))];source.players[0].status='playing';S=projectGame(source,0);let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload.viewData.blackjack.dealer.map(c=>({...c}))}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return{seen,firstRank:first.rank,secondRank:second.rank};});assert.equal(r.seen[0].rank,r.firstRank);assert.equal(r.seen[1].hidden,true);assert.equal(Object.hasOwn(r.seen[1],'rank'),false);assert.equal(Number.isInteger(r.secondRank),true);}finally{await browser.close();}});

test('Battle projection removes the value of face-down war cards',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'bataille','online');const r=await t.page.evaluate(async()=>{const source=net.state,hidden=clone(source.players[0].hand[0]),shown=clone(source.players[1].hand[0]);source.battleReveal=[{owner:0,card:hidden,hidden:true},{owner:1,card:shown,hidden:false}];S=projectGame(source,0);let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={projected:clone(payload.state.battleReveal),rendered:clone(payload.viewData.battle.reveals)}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return{seen,hiddenRank:hidden.rank,shownRank:shown.rank};});assert.equal(r.seen.projected[0].hidden,true);assert.equal(Object.hasOwn(r.seen.projected[0],'card'),false);assert.equal(Object.hasOwn(r.seen.rendered[0],'card'),false);assert.equal(r.seen.rendered[1].card.rank,r.shownRank);assert.equal(Number.isInteger(r.hiddenRank),true);}finally{await browser.close();}});
test('Cactus 3D adapter preserves projected card privacy online',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'cactus','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=clone(payload.viewData.cactus)}});net.state.phase='draw';net.state.turn=0;net.state.reveal=null;S=projectGame(net.state,0);renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return seen;});assert.equal(r.viewer,0);for(const p of r.players)for(const c of p.hand)if(c){assert.equal(c.hidden,true);assert.equal('rank' in c,false);assert.equal('suit' in c,false);}assert.ok(r.discard&&Number.isInteger(r.discard.rank));}finally{await browser.close();}});

test('Cactus 3D sees only engine-authorized peek cards',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'cactus','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=clone(payload.viewData.cactus)}});net.state.phase='peek';net.state.turn=0;S=projectGame(net.state,0);renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return seen.players[0].hand.map(c=>c&&({hidden:!!c.hidden,rank:c.rank??null,suit:c.suit??null}));});assert.equal(r[0].hidden,true);assert.equal(r[1].hidden,true);assert.equal(r[2].hidden,false);assert.equal(r[3].hidden,false);assert.ok(Number.isInteger(r[2].rank));assert.ok(Number.isInteger(r[3].rank));}finally{await browser.close();}});

test('Cactus 3D quick throw keeps the out-of-turn online action path',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'cactus','online');const r=await t.page.evaluate(async()=>{net.state.phase='draw';net.state.turn=1;const owner=0,index=net.state.players[owner].hand.findIndex(Boolean),card=net.state.players[owner].hand[index];net.state.discard[net.state.discard.length-1]={...net.state.discard.at(-1),rank:card.rank};S=projectGame(net.state,0);let interaction=null;SalonTableView.register('3d',{available:()=>true,render(payload){interaction=payload.interactions.cactus}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const before=legacyCactusCount(net.state.players[owner]);interaction('quick',index);return{removed:before-legacyCactusCount(net.state.players[owner]),owner:net.state.lastQuick?.owner,turn:net.state.turn};});assert.deepEqual(r,{removed:1,owner:0,turn:1});}finally{await browser.close();}});
test('Rummikub 3D exposes only the viewer rack and projected common table',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'rummikub','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=clone(payload.viewData.rummi)}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return{seen,own:clone(S.players[0].hand),opponent:clone(S.players[1].hand)};});assert.deepEqual(r.seen.hand,r.own);assert.ok(r.opponent.every(t=>t.hidden===true));assert.ok(r.seen.table.flat().every(t=>!t.hidden));}finally{await browser.close();}});

test('Rummikub 3D selection is local until an existing move action is sent',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'rummikub','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const id=S.players[0].hand[0].id,before={state:clone(S),packets:clone(__test.packets),random:__test.random};seen.interactions.rummi('select',id);const selected=[...selection],afterSelect={state:clone(S),packets:clone(__test.packets),random:__test.random};return{id,selected,before,afterSelect};});assert.deepEqual(r.selected,[r.id]);assert.deepEqual(r.afterSelect,r.before);}finally{await browser.close();}});

test('Rummikub 3D keeps old table tiles locked before first opening',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'rummikub','solo');const r=await t.page.evaluate(async()=>{player(S).opened=false;const old=S.table.flat()[0]||null;return{opened:player(S).opened,oldId:old?.id||null,refIds:S.refTable.flat().map(t=>t.id),canMoveOld:player(S).opened};});assert.equal(r.opened,false);assert.equal(r.canMoveOld,false);if(r.oldId)assert.ok(r.refIds.includes(r.oldId));}finally{await browser.close();}});

test('Métropole 3D payload contains board state but not the private event deck',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'metropole','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={city:clone(payload.viewData.city),stateHasEvents:Object.hasOwn(payload.state,'events')}}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});return{...seen,playerCount:S.players.length};});assert.equal(r.city.board.length,24);assert.equal(r.city.owners.length,24);assert.equal(r.city.houses.length,24);assert.equal(r.city.mortgaged.length,24);assert.equal(r.city.players.length,r.playerCount);assert.equal(r.stateHasEvents,false);assert.equal(r.city.board.every(c=>typeof c.name==='string'&&typeof c.type==='string'),true);}finally{await browser.close();}});

test('Métropole 3D roll delegates to the authoritative host action path',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'metropole','online');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});net.gameId='metropole';net.state.phase='roll';net.state.turn=0;S=projectGame(net.state,0);renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const before={moves:net.state.moves,packets:clone(__test.packets)};const ok=seen.interactions.city('roll');return{ok,before,remoteSeats:net.seats.slice(1).filter(seat=>seat?.conn?.open).length,after:{moves:net.state.moves,phase:net.state.phase,dice:clone(net.state.dice),packets:clone(__test.packets)}};});assert.equal(r.ok,true);assert.equal(r.after.moves,r.before.moves+1);assert.equal(Array.isArray(r.after.dice)&&r.after.dice.length,2);assert.equal(r.after.dice.every(n=>Number.isInteger(n)&&n>=1&&n<=6),true);const added=r.after.packets.slice(r.before.packets.length);assert.equal(added.length,r.remoteSeats);assert.ok(added.every(packet=>packet?.type==='state'&&packet?.event?.type==='roll'&&packet?.event?.actor===0));assert.equal(new Set(added.map(packet=>packet.revision)).size,1);}finally{await browser.close();}});


test('Echo 3D is playable while the hidden sequence stays out of the repeat payload',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'echo','online');const r=await t.page.evaluate(async()=>{net.gameId='echo';let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const watch={phase:seen.viewData.echo.phase,visible:[...seen.viewData.echo.sequence],authoritative:[...net.state.sequence]};const memorized=seen.interactions.echo('memorized');const repeat={phase:seen.viewData.echo.phase,visible:[...seen.viewData.echo.sequence],stateSequence:[...(seen.state.sequence||[])],authoritative:[...net.state.sequence]};while(net.state.phase==='repeat'){const index=net.state.sequence[net.state.input.length];if(!seen.interactions.echo('pad',index))throw Error('3D pad rejected');}const result={phase:net.state.phase,score:net.state.players[0].score,visible:[...seen.viewData.echo.sequence],input:[...net.state.input]};const continued=seen.interactions.echo('continue');return{watch,memorized,repeat,result,continued,after:{turn:net.state.turn,phase:net.state.phase,visible:[...seen.viewData.echo.sequence]}};});assert.equal(r.watch.phase,'watch');assert.equal(r.watch.visible.length,3);assert.deepEqual(r.watch.visible,r.watch.authoritative);assert.equal(r.memorized,true);assert.equal(r.repeat.phase,'repeat');assert.deepEqual(r.repeat.visible,[]);assert.deepEqual(r.repeat.stateSequence,[]);assert.equal(r.repeat.authoritative.length,3);assert.equal(r.result.phase,'result');assert.equal(r.result.score,6);assert.deepEqual(r.result.input,r.result.visible);assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'watch');assert.deepEqual(r.after.visible,[]);}finally{await browser.close();}});


test('Balloon 3D stays RNG-neutral and delegates pump, bank and continue to the engine',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'ballon','online');const r=await t.page.evaluate(async()=>{net.gameId='ballon';let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const randomBeforeRender=__test.random;for(let i=0;i<4;i++)renderGame(false);const randomAfterRender=__test.random;const beforePump={moves:net.state.moves,random:__test.random};const pump=seen.interactions.balloon('pump');const afterPump={moves:net.state.moves,pumps:net.state.pumps,random:__test.random};net.state.phase='play';net.state.pot=20;net.state.pumps=2;net.state.burst=false;S=projectGame(net.state,0);renderGame(false);const score=net.state.players[0].score,randomBeforeBank=__test.random,risk=seen.viewData.balloon.risk;const bank=seen.interactions.balloon('bank');const banked={phase:net.state.phase,score:net.state.players[0].score,random:__test.random};const continued=seen.interactions.balloon('continue');return{randomBeforeRender,randomAfterRender,beforePump,pump,afterPump,risk,score,randomBeforeBank,bank,banked,continued,after:{turn:net.state.turn,phase:net.state.phase,pot:net.state.pot,pumps:net.state.pumps}};});assert.equal(r.randomAfterRender,r.randomBeforeRender);assert.equal(r.pump,true);assert.equal(r.afterPump.moves,r.beforePump.moves+1);assert.equal(r.afterPump.pumps,1);assert.equal(r.afterPump.random,r.beforePump.random+1);assert.equal(r.risk,30);assert.equal(r.bank,true);assert.equal(r.banked.phase,'result');assert.equal(r.banked.score,r.score+20);assert.equal(r.banked.random,r.randomBeforeBank);assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'play');assert.equal(r.after.pot,0);assert.equal(r.after.pumps,0);}finally{await browser.close();}});


test('Echo 3D solo payload projects away the answer during repeat',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'echo','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const watch={view:[...seen.viewData.echo.sequence],state:[...(seen.state.sequence||[])]};const ok=seen.interactions.echo('memorized');return{ok,watch,repeat:{phase:S.phase,authoritative:[...S.sequence],view:[...seen.viewData.echo.sequence],state:[...(seen.state.sequence||[])]}};});assert.equal(r.ok,true);assert.equal(r.watch.view.length,3);assert.equal(r.watch.state.length,3);assert.equal(r.repeat.phase,'repeat');assert.equal(r.repeat.authoritative.length,3);assert.deepEqual(r.repeat.view,[]);assert.deepEqual(r.repeat.state,[]);}finally{await browser.close();}});

test('Anagram 3D submits through the engine without exposing the answer',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'anagrammes','online');const r=await t.page.evaluate(async()=>{net.gameId='anagrammes';let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const initial={phase:seen.viewData.anagram.phase,letters:[...seen.viewData.anagram.letters],clue:seen.viewData.anagram.clue,viewHasAnswer:Object.hasOwn(seen.viewData.anagram,'answer'),stateHasAnswer:Object.hasOwn(seen.state,'answer'),answer:net.state.answer,score:net.state.players[0].score};const submitted=seen.interactions.anagram('submit',net.state.answer);const result={phase:net.state.phase,score:net.state.players[0].score,feedback:seen.viewData.anagram.feedback};const continued=seen.interactions.anagram('continue');return{initial,submitted,result,continued,after:{turn:net.state.turn,phase:net.state.phase,stateHasAnswer:Object.hasOwn(seen.state,'answer'),viewHasAnswer:Object.hasOwn(seen.viewData.anagram,'answer')}};});assert.equal(r.initial.phase,'play');assert.equal(r.initial.letters.length,5);assert.equal(typeof r.initial.clue,'string');assert.equal(r.initial.viewHasAnswer,false);assert.equal(r.initial.stateHasAnswer,false);assert.equal(r.submitted,true);assert.equal(r.result.phase,'result');assert.equal(r.result.score,r.initial.score+5);assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'play');assert.equal(r.after.stateHasAnswer,false);assert.equal(r.after.viewHasAnswer,false);}finally{await browser.close();}});


test('Intrus 3D exposes only visual variants and validates spots through the engine',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'intrus','online');const r=await t.page.evaluate(async()=>{net.gameId='intrus';let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const answer=net.state.intrusIndex,wrong=(answer+1)%net.state.intrusCount,score=net.state.players[0].score;const initial={count:seen.viewData.intrus.count,tiles:[...seen.viewData.intrus.tiles],viewHasIndex:Object.hasOwn(seen.viewData.intrus,'intrusIndex'),stateHasIndex:Object.hasOwn(seen.state,'intrusIndex')};const wrongOk=seen.interactions.intrus('spot',wrong);const afterWrong={phase:net.state.phase,tried:[...net.state.tried],score:net.state.players[0].score,stateHasIndex:Object.hasOwn(seen.state,'intrusIndex')};const correctOk=seen.interactions.intrus('spot',answer);const result={phase:net.state.phase,tried:[...net.state.tried],score:net.state.players[0].score,viewHasIndex:Object.hasOwn(seen.viewData.intrus,'intrusIndex'),stateHasIndex:Object.hasOwn(seen.state,'intrusIndex'),tiles:[...seen.viewData.intrus.tiles]};const continued=seen.interactions.intrus('continue');return{answer,score,initial,wrongOk,afterWrong,correctOk,result,continued,after:{turn:net.state.turn,phase:net.state.phase,tried:[...net.state.tried],stateHasIndex:Object.hasOwn(seen.state,'intrusIndex')}};});assert.equal(r.initial.count,9);assert.equal(r.initial.tiles.filter(Boolean).length,1);assert.equal(r.initial.tiles[r.answer],true);assert.equal(r.initial.viewHasIndex,false);assert.equal(r.initial.stateHasIndex,false);assert.equal(r.wrongOk,true);assert.equal(r.afterWrong.phase,'play');assert.deepEqual(r.afterWrong.tried,[(r.answer+1)%r.initial.count]);assert.equal(r.afterWrong.score,r.score);assert.equal(r.afterWrong.stateHasIndex,false);assert.equal(r.correctOk,true);assert.equal(r.result.phase,'result');assert.equal(r.result.tried.length,2);assert.equal(r.result.score,r.score+20);assert.equal(r.result.viewHasIndex,false);assert.equal(r.result.stateHasIndex,false);assert.deepEqual(r.result.tiles,r.initial.tiles);assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'play');assert.deepEqual(r.after.tried,[]);assert.equal(r.after.stateHasIndex,false);}finally{await browser.close();}});


test('Code Secret 3D keeps the secret private until result and delegates guesses to the engine',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'code','online');const r=await t.page.evaluate(async()=>{net.gameId='code';let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const secret=[...net.state.secret],wrong=[...secret];wrong[0]=(wrong[0]+1)%6;const score=net.state.players[0].score;const initial={history:clone(seen.viewData.code3d.history),secret:[...seen.viewData.code3d.secret],viewHasSecret:Object.hasOwn(seen.viewData.code3d,'secret')&&seen.viewData.code3d.secret.length>0,stateHasSecret:Object.hasOwn(seen.state,'secret')};const wrongOk=seen.interactions.codePuzzle('guess',wrong);const afterWrong={phase:net.state.phase,history:clone(net.state.codeHistory),viewHistory:clone(seen.viewData.code3d.history),viewSecret:[...seen.viewData.code3d.secret],stateHasSecret:Object.hasOwn(seen.state,'secret')};const correctOk=seen.interactions.codePuzzle('guess',secret);const result={phase:net.state.phase,history:clone(net.state.codeHistory),score:net.state.players[0].score,viewSecret:[...seen.viewData.code3d.secret],stateSecret:[...(seen.state.secret||[])]};const continued=seen.interactions.codePuzzle('continue');return{secret,score,initial,wrongOk,afterWrong,correctOk,result,continued,after:{turn:net.state.turn,phase:net.state.phase,viewSecret:[...seen.viewData.code3d.secret],stateHasSecret:Object.hasOwn(seen.state,'secret')}};});assert.deepEqual(r.initial.history,[]);assert.deepEqual(r.initial.secret,[]);assert.equal(r.initial.viewHasSecret,false);assert.equal(r.initial.stateHasSecret,false);assert.equal(r.wrongOk,true);assert.equal(r.afterWrong.phase,'play');assert.equal(r.afterWrong.history.length,1);assert.equal(r.afterWrong.viewHistory.length,1);assert.deepEqual(r.afterWrong.viewSecret,[]);assert.equal(r.afterWrong.stateHasSecret,false);assert.equal(r.correctOk,true);assert.equal(r.result.phase,'result');assert.equal(r.result.history.length,2);assert.equal(r.result.score,r.score+52);assert.deepEqual(r.result.viewSecret,r.secret);assert.deepEqual(r.result.stateSecret,r.secret);assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'play');assert.deepEqual(r.after.viewSecret,[]);assert.equal(r.after.stateHasSecret,false);}finally{await browser.close();}});


test('Mini Golf 3D delegates physics to the engine and reuses the authoritative path',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'golf','online');const r=await t.page.evaluate(async()=>{net.gameId='golf';const course=GOLF_COURSES[net.state.stage-1];net.state.phase='play';net.state.turn=0;net.state.golfPos={x:course.hole.x-10,y:course.hole.y};net.state.golfStroke=0;net.state.golfPath=[];net.state.golfSunk=false;S=projectGame(net.state,0);let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen=payload}});renderGame(false);await SalonTableView.setMode('3d',{persistPreference:false});const before={moves:net.state.moves,random:__test.random,score:net.state.players[0].score,pos:clone(net.state.golfPos),course:clone(seen.viewData.golf3d.course)};const shot=seen.interactions.golf('shoot',{angle:0,power:5});const result={moves:net.state.moves,random:__test.random,score:net.state.players[0].score,phase:net.state.phase,stroke:net.state.golfStroke,sunk:net.state.golfSunk,path:clone(net.state.golfPath),viewPath:clone(seen.viewData.golf3d.path),viewPos:clone(seen.viewData.golf3d.pos)};const continued=seen.interactions.golf('continue');return{before,shot,result,continued,after:{turn:net.state.turn,phase:net.state.phase,stroke:net.state.golfStroke,path:clone(net.state.golfPath),pos:clone(net.state.golfPos)}};});assert.equal(Array.isArray(r.before.course.obstacles),true);assert.equal(Number.isFinite(r.before.course.hole.x)&&Number.isFinite(r.before.course.hole.y),true);assert.equal(r.shot,true);assert.equal(r.result.moves,r.before.moves+1);assert.equal(r.result.random,r.before.random);assert.equal(r.result.phase,'result');assert.equal(r.result.stroke,1);assert.equal(r.result.sunk,true);assert.equal(r.result.score,r.before.score+100);assert.equal(r.result.path.length>=2,true);assert.deepEqual(r.result.viewPath,r.result.path);assert.deepEqual(r.result.viewPos,r.result.path.at(-1).reduce((o,v,i)=>(o[i?'y':'x']=v,o),{}));assert.equal(r.continued,true);assert.equal(r.after.turn,1);assert.equal(r.after.phase,'play');assert.equal(r.after.stroke,0);assert.deepEqual(r.after.path,[]);assert.deepEqual(r.after.pos,{x:65,y:220});}finally{await browser.close();}});


test('Three.js hardening adapts mobile quality, motion and reusable geometry',async()=>{
 const source=await readFile(path.join(root,'shared/table-3d.js'),'utf8');
 const css=await readFile(path.join(root,'shared/table-3d.css'),'utf8');
 assert.match(source,/dataset\.motion!=='off'/);
 assert.doesNotMatch(source,/const motionAllowed=.*&&motionAllowed\(\)/);
 assert.match(source,/prefers-reduced-motion: reduce/);
 assert.match(source,/targetPixelRatio/);
 assert.match(source,/function handCardSlot\(count,index\)/);
 assert.match(source,/camera\.fov=aspect<\.72\?58:aspect<\.9\?50:aspect>1\.8\?37:39/);
 assert.match(source,/memory<=4\)\?1\.5:2/);
 assert.equal((source.match(/new THREE\.BoxGeometry\(\.62,\.9,\.085\)/g)||[]).length,1);
 assert.equal((source.match(/new THREE\.BoxGeometry\(1\.28,\.16,\.88\)/g)||[]).length,1);
 assert.match(source,/lostpointercapture/);
 assert.match(source,/function capturePointer\(id\)\{try\{/);
 assert.match(source,/cardDropRadius/);
 assert.match(css,/58svh/);
 assert.match(css,/54svh/);
 assert.match(css,/data-table-view="3d"\] \.table-column>\.scene-surface/);
 assert.match(css,/data-table-view="3d"\] \.table-column>\.arcade-arena/);
 assert.match(css,/data-table-view="3d"\] \.table-column>\.hand-panel/);
 assert.match(css,/data-table3d-presentation="full"/);
 assert.match(css,/height:100dvh/);
 assert.match(css,/\.table-3d-window-controls/);
 assert.match(css,/#game-actions\{position:fixed/);
});
