import assert from 'node:assert/strict';
import { test } from 'node:test';
import { readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';
const root=fileURLToPath(new URL('../../',import.meta.url));
const epoch=Date.UTC(2026,8,27,12);
async function table(){
 const browser=await chromium.launch({headless:true,executablePath:process.env.TABLE_BROWSER_EXECUTABLE});
 const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await context.route('**/*',async route=>{const url=new URL(route.request().url());if(url.origin!=='http://table.test')return route.fulfill({status:200,contentType:'text/javascript',body:''});const file=path.resolve(root,'.'+decodeURIComponent(url.pathname));if(!file.startsWith(root))return route.abort();try{const body=await readFile(file);const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json'};await route.fulfill({status:200,contentType:mime[path.extname(file)]||'application/octet-stream',body});}catch{await route.fulfill({status:404,body:''});}});
 await page.addInitScript(({epoch})=>{const c=window.__test={now:epoch,seed:123456789,random:0,packets:[],timers:new Map(),next:1};const NativeDate=Date;window.Date=class extends NativeDate{constructor(...a){super(...(a.length?a:[c.now]));}static now(){return c.now;}};Math.random=()=>{c.random++;c.seed=(Math.imul(c.seed,1664525)+1013904223)>>>0;return c.seed/4294967296;};const add=(kind,fn,delay=0)=>{const id=c.next++;c.timers.set(id,{kind,fn,delay:Number(delay),due:c.now+Number(delay)});return id;};window.setTimeout=(fn,d)=>add('timeout',fn,d);window.setInterval=(fn,d)=>add('interval',fn,d);window.clearTimeout=window.clearInterval=id=>c.timers.delete(id);window.requestAnimationFrame=fn=>add('frame',fn,16);window.cancelAnimationFrame=id=>c.timers.delete(id);c.advance=ms=>{c.now+=ms;};c.reset=()=>{c.now=epoch;c.seed=123456789;c.random=0;c.packets.length=0;};localStorage.setItem('table.v3.prefs',JSON.stringify({sound:false,motion:false,immersive:true,fast:false,light:false}));},{epoch});
 await page.goto('http://table.test/jeux.html');await page.evaluate(()=>{if(typeof houseEightAct!=='function'||typeof legacyCactusQuickUI!=='function')throw Error('final overrides missing');__test.connection=()=>({open:true,send:p=>__test.packets.push(JSON.parse(JSON.stringify(p))),close(){}});});return{browser,page,errors};}
const clone=v=>JSON.parse(JSON.stringify(v));
async function setup(page,id='huit',mode='solo',timed=false){return page.evaluate(({id,mode,timed})=>{__test.reset();net=freshNetwork();prefs.motion=false;prefs.sound=false;prefs.fast=false;prefs.immersive=true;applyPrefs();S=createGame(id,{mode,names:['A','B','C'],timeControl:{enabled:timed,initial:120,bonus:10,drawBonus:10}});view='game';gate=false;busy=false;selection.clear();showSuit=null;if(mode==='online'){net.active=true;net.role='host';net.me=0;net.connected=true;net.started=true;net.status='playing';net.matchId='test';net.revision=1;net.state=S;net.seats=S.players.map(p=>({name:p.name,lastSeq:0,conn:__test.connection()}));net.conn=__test.connection();S=projectGame(net.state,0);}renderGame(false);return Object.keys(GAMES);},{id,mode,timed});}
async function clean(page){return page.evaluate(()=>({state:clone(S),random:__test.random,packets:clone(__test.packets)}));}
let browser;
test('22 final game definitions survive repeated 2D refreshes',async()=>{const t=await table();browser=t.browser;try{const games=await setup(t.page);assert.equal(games.length,22);for(const id of games){await setup(t.page,id);const before=await clean(t.page);await t.page.evaluate(()=>{for(let i=0;i<5;i++)renderGame(false);});assert.deepEqual(await clean(t.page),before,id);}assert.deepEqual(t.errors,[]);}finally{await browser.close();}});
test('same seed and actions are independent of extra frames',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const run=extra=>t.page.evaluate(extra=>{const trace=[];for(let i=0;i<6&&S.phase!=='over';i++){const a=ai(S);trace.push({a,ok:act(S,a)});if(extra)for(let j=0;j<3;j++)renderGame(false);}return{state:clone(S),trace,random:__test.random};},extra);const a=await run(false);await setup(t.page);const b=await run(true);assert.deepEqual(b,a);}finally{await browser.close();}});
test('render is timing-neutral while the session tick settles the clock',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.clock.running=true;S.clock.lastAt=Date.now();const before=clone(S.clock);__test.advance(4000);renderGame(false);const afterRender=clone(S.clock);timingTick();const afterTick=clone(S.clock);return{before,afterRender,afterTick};});assert.deepEqual(r.afterRender,r.before);assert.equal(r.afterRender.remaining[0]-r.afterTick.remaining[0],4000);}finally{await browser.close();}});
test('session scheduling owns the clock run-state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.clock.running=false;S.clock.lastAt=Date.now();schedule();const afterSchedule=clone(S.clock);renderGame(false);return{afterSchedule,afterRender:clone(S.clock)};});assert.equal(r.afterSchedule.running,true);assert.deepEqual(r.afterRender,r.afterSchedule);}finally{await browser.close();}});
test('final guest handler preserves the authenticated seat index',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');const r=await t.page.evaluate(()=>{net.state.turn=2;const n=net.state.players[2].hand.length;handleGuestAction({seq:1,revision:1,matchId:'test',action:{type:'draw'}},2);return{drawn:net.state.players[2].hand.length-n,seq:net.seats[2].lastSeq,otherSeq:net.seats[1].lastSeq};});assert.deepEqual(r,{drawn:1,seq:1,otherSeq:0});}finally{await browser.close();}});
test('Cactus quick throw uses the authenticated guest seat even out of turn',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'cactus','online');const r=await t.page.evaluate(()=>{net.state.phase='draw';net.state.turn=0;const owner=2,index=net.state.players[owner].hand.findIndex(Boolean),card=net.state.players[owner].hand[index];net.state.discard[net.state.discard.length-1]={...net.state.discard.at(-1),rank:card.rank};const before=legacyCactusCount(net.state.players[owner]);handleGuestAction({seq:1,revision:1,matchId:'test',action:{type:'quick',index}},owner);return{removed:before-legacyCactusCount(net.state.players[owner]),owner:net.state.lastQuick?.owner,seq:net.seats[owner].lastSeq,otherSeq:net.seats[1].lastSeq,turn:net.state.turn};});assert.deepEqual(r,{removed:1,owner:2,seq:1,otherSeq:0,turn:0});}finally{await browser.close();}});
test('clock expiration uses the restored Eight rules',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo',true);const r=await t.page.evaluate(()=>{S.turn=0;S.phase='play';S.pendingDraw=6;S.attack='A';S.blockEight=false;S.clock.remaining[0]=0;S.clock.running=false;const before=S.players[0].hand.length;const ok=clockExpire(S,Date.now());return{ok,drawn:S.players[0].hand.length-before,pendingDraw:S.pendingDraw,attack:S.attack,turn:S.turn,reserve:S.clock.remaining[0]};});assert.equal(r.ok,true);assert.equal(r.drawn,6);assert.equal(r.pendingDraw,0);assert.equal(r.attack,null);assert.notEqual(r.turn,0);assert.equal(r.reserve,20000);}finally{await browser.close();}});
test('view controller switches renderers without touching game or network state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');const before=await clean(t.page);const r=await t.page.evaluate(async()=>{const calls=[];SalonTableView.register('test3d',{activate(){calls.push('activate')},render(payload){calls.push({gameId:payload.gameId,privateIndex:payload.privateIndex,online:payload.online,stateId:payload.state?.id})},deactivate(){calls.push('deactivate')}});const switched=await SalonTableView.setMode('test3d',{persistPreference:false});renderGame(false);const mode3d=SalonTableView.getMode();const back=await SalonTableView.setMode('2d',{persistPreference:false});return{switched,back,mode3d,mode2d:SalonTableView.getMode(),calls,hasStateView:Object.hasOwn(S,'tableView')||Object.hasOwn(S,'viewMode'),hasNetView:Object.hasOwn(net,'tableView')||Object.hasOwn(net,'viewMode')};});const after=await clean(t.page);assert.equal(r.switched.ok,true);assert.equal(r.mode3d,'test3d');assert.equal(r.back.ok,true);assert.equal(r.mode2d,'2d');assert.equal(r.hasStateView,false);assert.equal(r.hasNetView,false);assert.ok(r.calls.some(x=>typeof x==='object'&&x.gameId==='huit'&&x.privateIndex===0&&x.online===true&&x.stateId==='huit'));assert.deepEqual(after,before);}finally{await browser.close();}});

test('unavailable 3D leaves the effective renderer in 2D',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const before=await clean(t.page);const r=await t.page.evaluate(async()=>{const result=await SalonTableView.setMode('3d',{persistPreference:false});return{result,mode:SalonTableView.getMode(),dataset:document.documentElement.dataset.tableView};});assert.equal(r.result.ok,false);assert.equal(r.result.reason,'unavailable');assert.equal(r.mode,'2d');assert.equal(r.dataset,'2d');assert.deepEqual(await clean(t.page),before);}finally{await browser.close();}});

test('returning to 2D cancels a late asynchronous 3D activation',async()=>{const t=await table();browser=t.browser;try{await setup(t.page);const r=await t.page.evaluate(async()=>{let release;SalonTableView.register('3d',{prepare(){return new Promise(resolve=>{release=resolve})},render(){throw Error('late 3D render must not run')}});const pending=SalonTableView.setMode('3d',{persistPreference:false});await Promise.resolve();const back=await SalonTableView.setMode('2d',{persistPreference:false});release();const first=await pending;return{first,back,mode:SalonTableView.getMode(),dataset:document.documentElement.dataset.tableView};});assert.equal(r.back.ok,true);assert.equal(r.first.ok,false);assert.equal(r.first.reason,'superseded');assert.equal(r.mode,'2d');assert.equal(r.dataset,'2d');}finally{await browser.close();}});
test('Eight exposes a local view switch without mutating online state',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','online');await t.page.evaluate(()=>{SalonTableView.register('3d',{available:()=>document.documentElement.dataset.table3dSupported==='yes',render(){}});renderGame(false);});assert.equal(await t.page.locator('.table-view-switch').count(),1);const before=await clean(t.page);await t.page.click('[data-table-view-mode="3d"]');await t.page.waitForFunction(()=>SalonTableView.getMode()==='3d');assert.deepEqual(await clean(t.page),before);await t.page.click('[data-table-view-mode="2d"]');await t.page.waitForFunction(()=>SalonTableView.getMode()==='2d');assert.deepEqual(await clean(t.page),before);await setup(t.page,'oie','online');assert.equal(await t.page.locator('.table-view-switch').count(),0);}finally{await browser.close();}});

test('privacy gate withholds state from an active 3D renderer',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','local');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={state:payload.state,gated:payload.gated,canInteract:payload.canInteract}}});await SalonTableView.setMode('3d',{persistPreference:false});gate=true;seen=null;renderGame(false);return{seen,mode:SalonTableView.getMode()};});assert.equal(r.mode,'3d');assert.equal(r.seen.gated,true);assert.equal(r.seen.canInteract,false);assert.equal(r.seen.state,null);}finally{await browser.close();}});

test('3D interaction payload pauses while Eight waits for a suit choice',async()=>{const t=await table();browser=t.browser;try{await setup(t.page,'huit','solo');const r=await t.page.evaluate(async()=>{let seen=null;SalonTableView.register('3d',{available:()=>true,render(payload){seen={canInteract:payload.canInteract,playable:[...payload.viewData.playableIds]}}});await SalonTableView.setMode('3d',{persistPreference:false});showSuit='synthetic-choice';renderGame(false);return seen;});assert.equal(r.canInteract,false);assert.deepEqual(r.playable,[]);}finally{await browser.close();}});

